### ISSUE TITLE
full_example.py failed with no attribute 'init_decoder'

### ISSUE THREAD

**Issue by zuheo23** [daanzu/kaldi-active-grammar#46]
I have the following problem running the full_example.py

setup:
- windows 10
- pip install dragonfly2[kaldi]
- pip install kaldi-active-grammar
- 

`python full_example.py

Kaldi-Active-Grammar v1.8.3:
    If this free, open source engine is valuable to you, please consider donating
    https://github.com/daanzu/kaldi-active-grammar
    Disable message by calling `kaldi_active_grammar.disable_donation_message()`
Traceback (most recent call last):
  File "full_example.py", line 12, in <module>
    decoder = compiler.init_decoder()
AttributeError: 'Compiler' object has no attribute 'init_decoder'`

**Comment by daanzu** [comment]
Ah, sorry, that is because of some changes as I prepare to release v2.0 (Real Soon Now). Try checking out the repo's v1.8.3 tag and it should work I think. Let me know if not!

**Comment by daanzu** [comment]
https://github.com/daanzu/kaldi-active-grammar/blob/b39d21035f3baff574ba36daf73e48e227cbaedc/examples/full_example.py

**Comment by zuheo23** [comment]
The script runs with v1.8.3. Thanks.
