### ISSUE TITLE
kaldi_active_grammar v2.1.0 incompatible with dragonfly2 ?

### ISSUE THREAD

**Issue by Wil31** [daanzu/kaldi-active-grammar#52]
I have installed successfully the new versions of kaldi-active-grammar and dragonfly2 with 'pip install dragonfly2==0.30.1' and 'pip install kaldi-active-grammar==2.1.0'.
But any demo or script I try to run returns this message: 
```
  File "C:\Users\xxx\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\dragonfly\engines\__init__.py", line 132, in get_engine
    raise EngineError(message)
dragonfly.engines.base.engine.EngineError: Exception while initializing kaldi engine: Incompatible kaldi_active_grammar version
```

I am on Windows 10 and everything worked well with kaldi-active-grammar v1.8.1, I wanted to try the new version with the fixes and changes.

**Comment by daanzu** [comment]
Ah, yes, I should probably make that clearer in the release notes. It requires changes in the dragonfly side backend, which have now been merged into the master branch of dragonfly, but aren't in its latest published package. It should hopefully be released soon. In the meantime, you could install with: `pip install https://github.com/dictation-toolbox/dragonfly/archive/master.zip`

**Comment by Wil31** [comment]
Hello, the latest package of dragonfly2 is now up to date. So there is no issue now.
Thanks,  Cheers.
